name: Continuous Integration

on:
  push:
    branches: [main, develop]
    paths_ignore:
      [
        "**.md",
        ".env",
        ".gitignore",
        ".prettierrc",
        ".prettierignore",
        ".github",
        "LICENSE",
      ]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  ci:
    uses: Pinehood/ph-reusable-workflows/.github/workflows/node-ci.yml@main
    secrets: inherit
    with:
      ecr_repository: "ph-auto-alter-art-influ"
